# ─────────────────────────────────────────────────────────────────────────────
# Vivah — Multi-stage Production Dockerfile
# Node 22 Alpine | Next.js 15 standalone output | Prisma 5
#
# Stages:
#   deps     → install all dependencies (cached layer)
#   builder  → build Next.js + generate Prisma client
#   runner   → minimal runtime image (~150 MB vs ~1 GB dev image)
#
# Usage:
#   docker build -t vivah:latest .
#   docker run -p 3000:3000 -e DATABASE_URL="..." -e WEDDING_ID="vivah-2026" vivah:latest
#
# Or use docker-compose (recommended):
#   docker compose up --build
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1: deps ────────────────────────────────────────────────────────────
# Install all dependencies. Result is cached unless package.json or
# schema.prisma changes — keeps subsequent builds fast.
FROM node:22-alpine AS deps

# openssl is required by Prisma on Alpine
RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Copy only files needed to install dependencies
COPY package.json package-lock.json* ./
COPY prisma ./prisma/

# Install ALL deps (including devDependencies needed for build)
RUN npm ci --legacy-peer-deps

# ── Stage 2: builder ─────────────────────────────────────────────────────────
# Build the Next.js application and generate Prisma client.
FROM node:22-alpine AS builder

RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

# Carry over node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy full source
COPY . .

# Generate Prisma client for the target platform
RUN npx prisma generate

# Disable Next.js telemetry during build
ENV NEXT_TELEMETRY_DISABLED=1

# DATABASE_URL is needed at build time only for Prisma client type generation.
# Pass a placeholder — it is overridden at runtime via env vars.
# For SQLite local builds: file:./dev.db
# For PostgreSQL: postgresql://user:pass@host:5432/db
ARG DATABASE_URL="file:./dev.db"
ENV DATABASE_URL=${DATABASE_URL}

# Production build — output mode "standalone" (set in next.config.ts)
RUN npm run build

# ── Stage 3: runner ───────────────────────────────────────────────────────────
# Minimal production image — only what Next.js needs to serve the app.
# next.config.ts output: "standalone" produces a self-contained server.js.
FROM node:22-alpine AS runner

RUN apk add --no-cache libc6-compat openssl

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# ── Copy build artifacts from builder ────────────────────────────────────────

# Static assets (images, icons, public files)
COPY --from=builder /app/public ./public

# Next.js standalone output — contains server.js + all required node_modules
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# Static files generated by Next.js build (JS chunks, CSS, etc.)
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

# Prisma schema + migrations (needed at runtime for db:seed and migrations)
COPY --from=builder --chown=nextjs:nodejs /app/prisma ./prisma

# Prisma generated client (binary + types)
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.prisma    ./node_modules/.prisma
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/@prisma    ./node_modules/@prisma

# tsx for running the seed script (npx tsx prisma/seed.ts)
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/tsx        ./node_modules/tsx
COPY --from=builder --chown=nextjs:nodejs /app/node_modules/.bin/tsx   ./node_modules/.bin/tsx

# Switch to non-root user
USER nextjs

# ── Runtime configuration ─────────────────────────────────────────────────────
EXPOSE 3000

ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Runtime env vars (override these at docker run / compose time):
# DATABASE_URL  — SQLite: file:./prisma/dev.db | PostgreSQL: postgresql://...
# WEDDING_ID    — default seed ID: vivah-2026
ENV DATABASE_URL="file:./prisma/dev.db"
ENV WEDDING_ID="vivah-2026"

# Health check — Next.js responds on /api/wedding when DB is up
HEALTHCHECK --interval=30s --timeout=10s --start-period=30s --retries=3 \
  CMD wget -qO- http://localhost:3000/api/wedding || exit 1

# Start the standalone Next.js server
CMD ["node", "server.js"]
